---
ansible_user: administrator
ansible_host: "{{ lookup('passwordstore', 'IT/CBI/agents/{{ cbi_provider }}/{{ inventory_hostname }}/ip directory={{ password_store.it }}') }}"
ansible_become_password: "{{ lookup('passwordstore', 'IT/CBI/agents/{{ cbi_provider }}/{{ inventory_hostname }}/users/{{ ansible_user }}/password directory={{ password_store.it }}') }}"

# Removes the warning "Platform darwin on host xxx is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information."
ansible_python_interpreter: auto_silent