---
- name: CBI dedicated macOS agents playbooks
  hosts: dedicated_agent:&macos
  # Do not gather facts, it has been done in the main playbook site.yml
  gather_facts: no

  roles:
    - role: macos_autologon
      tags: [autologon]
