---
- name: Print facts
  debug:
    msg:
      - "inventory_hostname: {{ inventory_hostname | default('***Undefined***') }}"
      - "ansible_hostname: {{ ansible_hostname | default('***Undefined***') }}"
      - "ansible_fqdn: {{ ansible_fqdn | default('***Undefined***') }}"
      - "ansible_user: {{ ansible_user | default('***Undefined***') }}"
      - "ansible_default_ipv4.address: {{ ansible_default_ipv4.address | default('***Undefined***') }}"
      - "ansible_system: {{ ansible_system | default('***Undefined***') }}"
      - "ansible_os_family: {{ ansible_os_family | default('***Undefined***') }}"
      - "ansible_distribution: {{ ansible_distribution | default('***Undefined***') }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version | default('***Undefined***') }}"
      - "ansible_distribution_release: {{ ansible_distribution_release | default('***Undefined***') }}"
      - "ansible_distribution_version: {{ ansible_distribution_version | default('***Undefined***') }}"
      - "ansible_architecture: {{ ansible_architecture | default('***Undefined***') }}"
      - "ansible_processor_vcpus: {{ ansible_processor_vcpus | default('***Undefined***') }}"
      - "ansible_processor_cores: {{ ansible_processor_cores | default('***Undefined***') }}"
      - "group_names: {{ group_names | default('***Undefined***') }}"
      - "project: {{ project | default('***Undefined***') }}"
      - "jenkins_agent: {{ jenkins_agent | default('***Undefined***') }}"